name: Build and Release Kernel with no SUSFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive
  ROOT_DIR_PREFIX: "OP13-A15"
  BRANCH: "android15-6.6"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free disk space
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq curl
          curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash


      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3-pip \
            curl \
            git \
            zip \
            unzip \
            gcc \
            g++ \
            make \
            ninja-build \
            file \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            wget \
            build-essential \
            python3-dev \
            python3-setuptools \
            rsync \
            ccache

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G

      - name: Install Latest Pahole
        run: |
          sudo apt-get remove --purge -y dwarves
          sudo apt-get install -y git build-essential libdw-dev zlib1g-dev
          git clone --recurse-submodules https://git.kernel.org/pub/scm/devel/pahole/pahole.git
          cd pahole
          cmake .
          sudo make install

      - name: Setup Python and Repo Tool
        run: |
          python3 -m pip install --upgrade pip
          pip3 install gitpython xmltodict
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          export PATH=$HOME/bin:$PATH  # Add $HOME/bin to PATH
          echo "$HOME/.bin" >> $GITHUB_PATH
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install repo tool to $HOME/bin
        run: |
         mkdir -p $HOME/bin
         wget -O $HOME/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
         chmod a+x $HOME/bin/repo
         export PATH=$HOME/bin:$PATH
         repo --version


      - name: Configure Build Directory
        run: |
          ROOT_DIR="${ROOT_DIR_PREFIX}-$(date +'%Y-%m-%d-%I-%M-%p')-release"
          echo "ROOT_DIR=${ROOT_DIR}" >> $GITHUB_ENV
          mkdir -p "builds/${ROOT_DIR}"
          cd "builds/${ROOT_DIR}"

      - name: Clone Required Repositories
        working-directory: builds/${{ env.ROOT_DIR }}
        run: |
          git clone https://github.com/TheWildJames/AnyKernel3.git -b $BRANCH
          #git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
          #git clone https://github.com/WildPlusKernel/kernel_patches.git

      - name: Setup Kernel Source
        working-directory: builds/${{ env.ROOT_DIR }}
        run: |
          mkdir -p kernel_platform/oneplus13
          cd kernel_platform/oneplus13
          repo init -u https://github.com/cabagekiller/kernel_manifest.git -b oneplus/sm8750 -m oneplus13_v.xml --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

     
      - name: Build Kernel
        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13/
        run: |
          cd kernel_platform
          mkdir out
          cd ..
          pwd
          ls -la kernel_platform/build
          export PATH="/usr/lib/ccache:$PATH"
          # Build with bazel
          ./kernel_platform/build_with_bazel.py -t sun perf
            
      - name: Debug Working Directory
        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13/kernel_platform/out/dist
        run: |         
          pwd
          ls -l

      - name: Create ZIP Package
        working-directory: builds/${{ env.ROOT_DIR }}
        run: |
          cp kernel_platform/oneplus13/kernel_platform/out/dist/Image AnyKernel3/Image
          cp kernel_platform/oneplus13/kernel_platform/out/dist/Image.lz4 AnyKernel3/Image.lz4
          cd AnyKernel3  # Move to AnyKernel3 directory
          ZIP_NAME="Anykernel3-OP13-A15-android15-6.6-KernelSUNext-SUSFS-$(date +'%Y-%m-%d-%H-%M-%S').zip"
          echo "Creating zip file $ZIP_NAME..."
          zip -r "../$ZIP_NAME" ./*
          ls -lh "../$ZIP_NAME"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV

      - name: Publish Release
        run: |
          # Change to the correct directory
          cd "./builds/${{ env.ROOT_DIR }}"

          # Debugging variables
          echo "ZIP_NAME: ${{ env.zip_name }}"
          ZIP_FILE_PATH="${GITHUB_WORKSPACE}/builds/${{ env.ROOT_DIR }}/${{ env.zip_name }}"
          echo "ZIP_FILE_PATH: $ZIP_FILE_PATH"

          # Validate ZIP file existence
          if [ -f "$ZIP_FILE_PATH" ]; then
              echo "ZIP file found: $ZIP_FILE_PATH"
          else
              echo "Error: ZIP file not found at $ZIP_FILE_PATH!"
              exit 1
          fi

          # Define the repository name if not already set
          REPO_NAME=${REPO_NAME:-$GITHUB_REPOSITORY}

          # Create a release using the GitHub CLI
          gh release create "v${{ env.BRANCH }}-$(date +'%Y.%m.%d-%H%M%S')" "$ZIP_FILE_PATH" \
            --repo "$REPO_NAME" \
            --title "OP13 A15 ${{ env.BRANCH }} With KernelSU & SUSFS" \
            --notes "Kernel release" \
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13/kernel_platform/out/*.log
            builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13/kernel_platform/**/*.rej
          retention-days: 5
